### ISSUE TITLE
적용할 에셋 찾기 (라이센스 확인 필요)

### ISSUE THREAD

**Issue by upa-r-upa** [not-blond-beard/savor22b#198]
- 타일셋(집/마을) 관련 에셋과
- 농장 에셋
- 부엌 에셋

**Comment by Atralupus** [comment]
기존 프로토타입에서 쓰려고 했던 에셋 중 아직 사용 가능한 것
- https://leo-red.itch.io/lucid-icon-pack
- https://crusenho.itch.io/complete-ui-essential-pack
- https://shononoki.itch.io/rpg-music-pack-svl

이젠 안되는 것
- https://jamiebrownhill.itch.io/solaria-demo

**Comment by upa-r-upa** [comment]
https://limezu.itch.io/serenevillagerevamped
https://limezu.itch.io/serenevillage
이건 외부 타일셋으로 쓸만해보이구요

https://limezu.itch.io/moderninteriors
이건 내부 인테리어 필요하다면 쓸 수 있을 것 같아요

https://limezu.itch.io/kitchen
이건 주방용

https://cainos.itch.io/pixel-art-top-down-basic
이건 다른 에셋인데 던전 들어가는 입구랑 던전 건물 내부?? 표현하기 적합할 것 같아요

**Comment by upa-r-upa** [comment]
결론

농장/집/마을(타일셋) -> NFT 제외 가능, 크레딧
https://danieldiggle.itch.io/sunnyside

부엌 -> CC BY
https://limezu.itch.io/kitchen

**Comment by upa-r-upa** [comment]
부엌 UI https://srtoasty.itch.io/ui-assets-pack-2
